version: '3'


services: 
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - "27100:27017"
    networks:
      - my-network
    command: ["--bind_ip", "0.0.0.0"]

      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8008:8000"
    depends_on: 
      - mongo
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


  
